name: fast_equatable_lint_example
description: Package with every examples for the fast_equatable_lint package
version: 0.1.0

publish_to: none

environment:
  sdk: ">3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.3.0
  fast_equatable: ^1.1.0

dev_dependencies:
  custom_lint: ^0.6.4
  fast_equatable_lint:
    path: ../
