name: fast_equatable_lint_example
description: Package with every examples for the fast_equatable_lint package
version: 0.1.0

publish_to: none

environment:
  sdk: ">3.0.0 <4.0.0"

dependencies:
  analyzer: ^7.3.0
  fast_equatable: ^1.3.1

dev_dependencies:
  fast_equatable_lint:
    path: ../
