name: fast_equatable_lint
version: 0.4.1
description: This is a set of rules to make classes using FastEquatable more maintainable. We validate that every fields in an FastEquatable class is linked to the hashParameters getter.
homepage: https://github.com/FaFre/fast_equatable_lint

environment:
  sdk: ">3.0.0 <4.0.0"

dependencies:
  analyzer: ^7.3.0
  analyzer_plugin: ^0.13.0
  collection: ^1.16.0
  custom_lint_builder: ^0.8.0
  fast_equatable: ^1.3.1
  source_gen: ^2.0.0
